gerrit_plugin(
  name = 'its-jira',
  srcs = glob(['src/main/java/**/*.java']),
  resources = glob(['src/main/resources/**/*']),
  manifest_entries = [
    'Gerrit-Module: com.googlesource.gerrit.plugins.its.jira.JiraModule',
    'Gerrit-InitStep: com.googlesource.gerrit.plugins.its.jira.InitJira',
    'Gerrit-ReloadMode: reload',
    'Implementation-Title: Jira ITS Plugin',
    'Implementation-URL: http://www.gerritforge.com',
    'Implementation-Vendor: GerritForge LLP',
  ],
  deps = [
    '//plugins/its-base:its-base__plugin',
    '//plugins/its-jira/lib/jira:jira-rest-java-client-api',
    '//plugins/its-jira/lib/jira:jira-rest-java-client-core',
    '//plugins/its-jira/lib/jira:atlassian-util-concurrent',
    '//plugins/its-jira/lib/jira:sal-api',
    '//plugins/its-jira/lib/jira:atlassian-event',
    '//plugins/its-jira/lib/jira:atlassian-httpclient-api',
    '//plugins/its-jira/lib/jira:atlassian-httpclient-spi',
    '//plugins/its-jira/lib/jira:atlassian-httpclient-apache-httpcomponents',
    '//plugins/its-jira/lib/jira:spring-beans',
    '//plugins/its-jira/lib/jira:httpclient',
    '//plugins/its-jira/lib/jira:httpclient-cache',
    '//plugins/its-jira/lib/jira:httpasyncclient',
    '//plugins/its-jira/lib/jira:httpasyncclient-cache',
    '//plugins/its-jira/lib/jira:httpcore-nio',
    '//plugins/its-jira/lib/jira:javax.ws.rs-api',
    '//plugins/its-jira/lib/jira:jersey-client',
    '//plugins/its-jira/lib/jira:jersey-common',
    '//plugins/its-jira/lib/jira:jersey-guava',
    '//plugins/its-jira/lib/jira:hk2-api',
    '//plugins/its-jira/lib/jira:hk2-utils',
    '//plugins/its-jira/lib/jira:hk2-locator',
    '//plugins/its-jira/lib/jira:javax.inject',
    '//plugins/its-jira/lib/jira:jettison',
  ],
)
